address: '0.0.0.0:80'
hosts: ['*']

file_root: 'resources/www'
template_root: 'resources/templates'

dir_listing:
  enabled: true

  all_viewable: false
  show_symlinks: false
  show_hidden: false

routing_table: { }

cgi_executors: { }

basic_auth: { }
