address: '0.0.0.0:443'

file_root: 'resources/www'
template_root: 'resources/templates'

dir_listing:
  enabled: true

  all_viewable: false
  show_symlinks: true
  show_hidden: false

routing_table:
  '@/': '/index.html'
  '@/about': '/about.html'

  '@/{image_name}/img': '/files/images/[image_name].jpg'
  '@/is_prime/{number:[0-9]{3\}}': '/files/prime_cgi.py?n=[number]'

  '@/pdfs/{pdf_name:\\w+}': '/files/pdfs/[pdf_name].pdf'
  '/pdfs': '/files/pdfs'

cgi_executors:
  py: 'python3'
  pl: 'perl'
  sh: '/usr/bin/bash'

basic_auth:
  secret_realm:
    credentials:
      - 'user1:$2b$08$v3DJthbkT6UlAkh9/U6MvOkiTO.iAhGsTHObky2MfadqWlsWX5sIe'
      - 'user2:$2a$10$v4hJszPeQhDm.4ncPEkpm.QCvckw.cs3rKQNNjdwCNLYeIixU2ALK'
    routes:
      - '@/files/secrets.html'
      - '/files/restricted'
  club_realm:
    credentials:
      - 'supersecretuser:$2b$08$v3DJthbkT6UlAkh9/U6MvOkiTO.iAhGsTHObky2MfadqWlsWX5sIe'
    routes:
      - '/the_club'

tls:
  cert_path: 'resources/cert.pem'
  key_path: 'resources/key.pem'
