address: "0.0.0.0:1440"

file_root: "resources/www"
template_root: "resources/templates"

cgi_executors:
    py: "python3"
    pl: "perl"

routing_table:
    "@/": "/index.html"
    "@/cgi": "/files/test_cgi.py"
    "/calc": "/files/calc"
    "/{image_name}/img": "/files/images/[image_name].jpg"
