address: "0.0.0.0:1440"

file_root: "resources/www"
template_root: "resources/templates"

cgi_executors:
    py: "python3"
    pl: "perl"

routing_table:
    "@/": "/index.html"
    "@/cgi": "/files/test_cgi.py"
    "@/{image_name:[a-zA-Z]+}/img": "/files/images/[image_name].jpg"
    "@/test/calc/pdfs/{pdf_name}": "/files/calc/[pdf_name].pdf"
    "/test/calc": "/files/calc"
